"""Data models for FRIS with N/A handling per FRIS-13."""

from dataclasses import dataclass, field
from typing import Optional

NA_STRING = "N/A"

@dataclass
class StockInfo:
    """Stock information with explicit N/A handling for missing fields."""
    ticker: str
    company_name: str
    sector: Optional[str] = None
    industry: Optional[str] = None
    market_cap: Optional[float] = None
    current_price: Optional[float] = None
    pe_ratio: Optional[float] = None
    pb_ratio: Optional[float] = None
    description: Optional[str] = None

    @property
    def sector_display(self) -> str:
        """Return sector or N/A string."""
        return self.sector if self.sector else NA_STRING

    @property
    def industry_display(self) -> str:
        """Return industry or N/A string."""
        return self.industry if self.industry else NA_STRING

    @property
    def market_cap_display(self) -> str:
        """Return market cap formatted or N/A string."""
        if self.market_cap is None:
            return NA_STRING
        if self.market_cap >= 1e12:
            return f"${self.market_cap / 1e12:.2f}T"
        elif self.market_cap >= 1e9:
            return f"${self.market_cap / 1e9:.2f}B"
        elif self.market_cap >= 1e6:
            return f"${self.market_cap / 1e6:.2f}M"
        return f"${self.market_cap:.2f}"

    @property
    def pe_ratio_display(self) -> str:
        """Return P/E ratio or N/A string."""
        if self.pe_ratio is None:
            return NA_STRING
        return f"{self.pe_ratio:.2f}"

    @property
    def pb_ratio_display(self) -> str:
        """Return P/B ratio or N/A string."""
        if self.pb_ratio is None:
            return NA_STRING
        return f"{self.pb_ratio:.2f}"

@dataclass
class StockSearchResult:
    """Result of topic-based stock search."""
    stocks: list[StockInfo]
    matched_industries: list[str]
    search_topic: str
    total_count: int


@dataclass
class EarningsData:
    """Earnings data for a stock."""
    ticker: str
    earnings_date: Optional[str] = None  # ISO format date
    eps_current: Optional[float] = None  # Trailing EPS (TTM)
    eps_forward: Optional[float] = None  # Forward EPS from guidance
    revenue: Optional[float] = None  # Most recent revenue
    revenue_yoy_change: Optional[float] = None  # YoY change percentage
    earnings_surprise: Optional[float] = None  # vs estimates if available
    data_source: str = "yfinance"
    fetched_at: Optional[str] = None  # ISO timestamp


@dataclass
class QuarterlyData:
    """Quarterly financial data for a stock."""
    ticker: str
    quarter: str  # "Q1", "Q2", "Q3", "Q4"
    year: int
    eps: Optional[float] = None
    revenue: Optional[float] = None
    revenue_yoy_change: Optional[float] = None
    report_date: Optional[str] = None  # ISO format date
    data_source: str = "yfinance"
    fetched_at: Optional[str] = None  # ISO timestamp


@dataclass
class KeyMetricsDetail:
    """Key financial metrics for stock summary."""
    eps_current: Optional[float] = None
    eps_forward: Optional[float] = None
    revenue: Optional[float] = None
    revenue_yoy_change: Optional[float] = None
    market_cap: Optional[float] = None
    pe_ratio: Optional[float] = None
    pb_ratio: Optional[float] = None
    current_price: Optional[float] = None


@dataclass
class StockSummary:
    """Business summary for a stock generated by LLM.

    FRIS-15: Business model, recent performance, competitive landscape, risk factors
    FRIS-16: Each summary is a separate document (JSON)
    FRIS-17: Includes company name, ticker, industry, period, key metrics
    FRIS-19: Cites data sources
    FRIS-23: Returns as structured JSON
    FRIS-24: Includes ticker, company_name, industry, period, summary_text, key_metrics
    FRIS-25: Includes data freshness timestamp
    """
    ticker: str
    company_name: str
    industry: str
    reporting_period: str  # e.g., "Q4 2024" or "FY 2024"
    summary_text: str  # Business model, performance, competitive landscape, risks
    key_metrics: KeyMetricsDetail
    data_sources: list[str]  # Citations (e.g., ["yfinance"])
    generated_at: str  # ISO timestamp when summary was generated
    model_used: str  # LLM model name (e.g., "gpt-4o-mini")

    def to_dict(self) -> dict:
        """Convert to dictionary for JSON serialization."""
        return {
            "ticker": self.ticker,
            "company_name": self.company_name,
            "industry": self.industry,
            "reporting_period": self.reporting_period,
            "summary_text": self.summary_text,
            "key_metrics": {
                "eps_current": self.key_metrics.eps_current,
                "eps_forward": self.key_metrics.eps_forward,
                "revenue": self.key_metrics.revenue,
                "revenue_yoy_change": self.key_metrics.revenue_yoy_change,
                "market_cap": self.key_metrics.market_cap,
                "pe_ratio": self.key_metrics.pe_ratio,
                "pb_ratio": self.key_metrics.pb_ratio,
                "current_price": self.key_metrics.current_price,
            },
            "data_sources": self.data_sources,
            "generated_at": self.generated_at,
            "model_used": self.model_used,
        }
